version: "3"

services: 
  proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
    labels: 
      - "traefik.http.routers.redirs.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.middlewares.test-auth.basicauth.users=admin:$$apr1$$ZAhx0FA1$$G8.pUHAJA2ImgGRejJS2d/"
      - "traefik.http.routers.redirs.middlewares=test-auth"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml

  app:
    image: app:v2
    container_name: appv3
    labels: 
      - "traefik.http.routers.app.rule=Host(`apache.app.test`)" # Required added the host on host file
      - "traefik.http.services.app.loadbalancer.server.port=8081"

  nginx:
    image: nginx
    labels: 
      - "traefik.http.routers.nginx.rule=Host(`nginx.app.test`)" # Required added the host on host file