version: "3"

services: 
  proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
  nginx:
    image: nginx
    labels: 
      - "traefik.http.routers.nginx.rule=Host(`nginx.app.test`) && path(`/traefik`)" # Required added the host on host file
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/traefik" # Path to remove
      - "traefik.http.routers.nginx.middlewares=test-stripprefix" # Used declared middleware
