version: "3"

services: 
  proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
  app:
    image: app:v2
    container_name: app2v2
    labels: 
      - "traefik.http.routers.app.rule=Host(`apache.app.test`)" # Required added the host on host file
      - "traefik.http.services.app.loadbalancer.server.port=8081"